#!/bin/bash
flags="$@"
zenity --progress --text="Chrome is loading" --pulsate --no-cancel --title="Google Chrome" &
zen=$!
/usr/bin/google-chrome "$@" &
until pid=$(pidof chrome); do
  echo -n "."
done
kill -9 $zen
